development:
  adapter: postgresql
  database: runningclubmanagement_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: runningclubmanagement_test
  host: localhost
  min_messages: warning
  username: